import tkinter as tk
from tkinter import *
from PIL import ImageTk,Image
from tkinter import messagebox
import os
py=sys.executable

def message():
    messagebox.showinfo("Savarankiškas darbas", "Gvidas Rimeikis PS9")
    
def dieta():
    root.destroy()
    os.system('%s %s' % (py, 'dieta.py'))
def BMI():
    root.destroy()
    os.system('%s %s' % (py, 'bmi.py'))
def pratimai():
    root.destroy()
    os.system('%s %s' % (py, 'pratimai.py'))

#raumenų dalys
def openChest():
    topChest = Toplevel()
    topChest.title ('Krutinės pratimai')
    topChest.geometry("1000x700")
    topChest.resizable(width=False, height=False)
    first_textbox = Text(topChest, width=25, height=45, borderwidth = 2, bg = "black")
    third_textbox = Text(topChest, width=105, height=45, borderwidth = 2)
    def spaudimai():
        c1 = ImageTk.PhotoImage(Image.open("images/spaudimai1.png"))
        cc1 = Label(topChest, image = c1)
        cc1.place(x=210,y=0)
        c2 = ImageTk.PhotoImage(Image.open("images/spaudimai2.png"))
        cc2 = Label(topChest, image = c2)
        cc2.place(x=210,y=234)
        c3 = ImageTk.PhotoImage(Image.open("images/spaudimai3.png"))
        cc3 = Label(topChest, image = c3)
        cc3.place(x=210,y=468)
        cc.config( height = 250, width = 700, bd = 0) #it works, dont touch
    def spaudimaiaparate():
        c1 = ImageTk.PhotoImage(Image.open("images/tspaudimai1.png"))
        cc1 = Label(topChest, image = c1)
        cc1.place(x=210,y=0)
        c2 = ImageTk.PhotoImage(Image.open("images/tspaudimai2.png"))
        cc2 = Label(topChest, image = c2)
        cc2.place(x=210,y=234)
        c3 = ImageTk.PhotoImage(Image.open("images/tspaudimai3.png"))
        cc3 = Label(topChest, image = c3)
        cc3.place(x=210,y=468)
        cc.config( height = 250, width = 700, bd = 0)
    def plesimai():
        c1 = ImageTk.PhotoImage(Image.open("images/plesimai1.png"))
        cc1 = Label(topChest, image = c1)
        cc1.place(x=210,y=0)
        c2 = ImageTk.PhotoImage(Image.open("images/plesimai2.png"))
        cc2 = Label(topChest, image = c2)
        cc2.place(x=210,y=234)
        c3 = ImageTk.PhotoImage(Image.open("images/plesimai3.png"))
        cc3 = Label(topChest, image = c3)
        cc3.place(x=210,y=468)
        cc.config( height = 250, width = 700, bd = 0)
        
    cbutton1 = Button(topChest, text = "Spaudimai", command = spaudimai)
    cbutton1.place(x=30,y=50)
    cbutton1.config( height = 5, width = 20, bd = 2)
    cbutton2 = Button(topChest, text = "Spaudimai treniruokliuose")
    cbutton2.place(x=30,y=150)
    cbutton2.config( height = 5, width = 20, bd = 2, command = spaudimaiaparate)
    cbutton3 = Button(topChest, text = "Plėšimai")
    cbutton3.place(x=30,y=250)
    cbutton3.config( height = 5, width = 20, bd = 2, command = plesimai)
    first_textbox.grid(column=1, row=1)  
    third_textbox.grid(column=2, row=1, rowspan=2)
    topChest.mainloop()
def openBack():
    topBack = Toplevel()
    topBack.title ('Nugaros pratimai')
    topBack.geometry("1000x700")
    topBack.resizable(width=False, height=False)
    first_textbox = Text(topBack, width=25, height=45, borderwidth = 2, bg = "black")
    third_textbox = Text(topBack, width=105, height=45, borderwidth = 2)
    def prisitraukimai():
        c1 = ImageTk.PhotoImage(Image.open("images/prisitraukimai1.png"))
        cc1 = Label(topBack, image = c1)
        cc1.place(x=210,y=0)
        c2 = ImageTk.PhotoImage(Image.open("images/prisitraukimai2.png"))
        cc2 = Label(topBack, image = c2)
        cc2.place(x=210,y=234)
        c3 = ImageTk.PhotoImage(Image.open("images/prisitraukimai3.png"))
        cc3 = Label(topBack, image = c3)
        cc3.place(x=210,y=468)
        cc.config( height = 250, width = 700, bd = 0)
    def traukapilvo():
        c1 = ImageTk.PhotoImage(Image.open("images/ptrauka1.png"))
        cc1 = Label(topBack, image = c1)
        cc1.place(x=210,y=0)
        c2 = ImageTk.PhotoImage(Image.open("images/ptrauka2.png"))
        cc2 = Label(topBack, image = c2)
        cc2.place(x=210,y=234)
        c3 = ImageTk.PhotoImage(Image.open("images/ptrauka3.png"))
        cc3 = Label(topBack, image = c3)
        cc3.place(x=210,y=468)
        cc.config( height = 250, width = 700, bd = 0)
    def vtrauka():
        c1 = ImageTk.PhotoImage(Image.open("images/vtrauka1.png"))
        cc1 = Label(topBack, image = c1)
        cc1.place(x=210,y=0)
        c2 = ImageTk.PhotoImage(Image.open("images/vtrauka2.png"))
        cc2 = Label(topBack, image = c2)
        cc2.place(x=210,y=234)
        c3 = ImageTk.PhotoImage(Image.open("images/vtrauka3.png"))
        cc3 = Label(topBack, image = c3)
        cc3.place(x=210,y=468)
        cc.config( height = 250, width = 700, bd = 0)
        
    cbutton1 = Button(topBack, text = "Prisitraukimai", command = prisitraukimai)
    cbutton1.place(x=30,y=50)
    cbutton1.config( height = 5, width = 20, bd = 2)
    cbutton2 = Button(topBack, text = "Trauka prie pilvo")
    cbutton2.place(x=30,y=150)
    cbutton2.config( height = 5, width = 20, bd = 2, command = traukapilvo)
    cbutton3 = Button(topBack, text = "Trauka iš viršaus")
    cbutton3.place(x=30,y=250)
    cbutton3.config( height = 5, width = 20, bd = 2, command = vtrauka)
    first_textbox.grid(column=1, row=1)  
    third_textbox.grid(column=2, row=1, rowspan=2)
    topBack.mainloop()
def openAbs():
    topAbs = Toplevel()
    topAbs.title ('Preso pratimai')
    topAbs.geometry("1000x700")
    topAbs.resizable(width=False, height=False)
    first_textbox = Text(topAbs, width=25, height=45, borderwidth = 2, bg = "black")
    third_textbox = Text(topAbs, width=105, height=45, borderwidth = 2)
    def kojukelimas():
        c1 = ImageTk.PhotoImage(Image.open("images/kojukelimas1.png"))
        cc1 = Label(topAbs, image = c1)
        cc1.place(x=210,y=0)
        c2 = ImageTk.PhotoImage(Image.open("images/kojukelimas2.png"))
        cc2 = Label(topAbs, image = c2)
        cc2.place(x=210,y=234)
        c3 = ImageTk.PhotoImage(Image.open("images/kojukelimas3.png"))
        cc3 = Label(topAbs, image = c3)
        cc3.place(x=210,y=468)
        cc.config( height = 250, width = 700, bd = 0)
    def kamuolys():
        c1 = ImageTk.PhotoImage(Image.open("images/kamuolys1.png"))
        cc1 = Label(topAbs, image = c1)
        cc1.place(x=210,y=0)
        c2 = ImageTk.PhotoImage(Image.open("images/kamuolys2.png"))
        cc2 = Label(topAbs, image = c2)
        cc2.place(x=210,y=234)
        c3 = ImageTk.PhotoImage(Image.open("images/kamuolys3.png"))
        cc3 = Label(topAbs, image = c3)
        cc3.place(x=210,y=468)
        cc.config( height = 250, width = 700, bd = 0)
    def zeme():
        c1 = ImageTk.PhotoImage(Image.open("images/presas1.png"))
        cc1 = Label(topAbs, image = c1)
        cc1.place(x=210,y=0)
        c2 = ImageTk.PhotoImage(Image.open("images/presas2.png"))
        cc2 = Label(topAbs, image = c2)
        cc2.place(x=210,y=234)
        c3 = ImageTk.PhotoImage(Image.open("images/presas3.png"))
        cc3 = Label(topAbs, image = c3)
        cc3.place(x=210,y=468)
        cc.config( height = 250, width = 700, bd = 0)
        
    cbutton1 = Button(topAbs, text = "Kojų kelimas", command = kojukelimas)
    cbutton1.place(x=30,y=50)
    cbutton1.config( height = 5, width = 20, bd = 2)
    cbutton2 = Button(topAbs, text = "Pratimai su kamuoliu")
    cbutton2.place(x=30,y=150)
    cbutton2.config( height = 5, width = 20, bd = 2, command = kamuolys)
    cbutton3 = Button(topAbs, text = "Pratimai ant žemės")
    cbutton3.place(x=30,y=250)
    cbutton3.config( height = 5, width = 20, bd = 2, command = zeme)
    first_textbox.grid(column=1, row=1)  
    third_textbox.grid(column=2, row=1, rowspan=2)
    topAbs.mainloop()
def openArms():
    topArms = Toplevel()
    topArms.title ('Rankų pratimai')
    topArms.geometry("1000x700")
    topArms.resizable(width=False, height=False)
    first_textbox = Text(topArms, width=25, height=45, borderwidth = 2, bg = "black")
    third_textbox = Text(topArms, width=105, height=45, borderwidth = 2)
    def bicepsai():
        c1 = ImageTk.PhotoImage(Image.open("images/biceps1.png"))
        cc1 = Label(topArms, image = c1)
        cc1.place(x=210,y=0)
        c2 = ImageTk.PhotoImage(Image.open("images/biceps2.png"))
        cc2 = Label(topArms, image = c2)
        cc2.place(x=210,y=234)
        c3 = ImageTk.PhotoImage(Image.open("images/biceps3.png"))
        cc3 = Label(topArms, image = c3)
        cc3.place(x=210,y=468)
        cc.config( height = 250, width = 700, bd = 0)
    def tricepsai():
        c1 = ImageTk.PhotoImage(Image.open("images/triceps1.png"))
        cc1 = Label(topArms, image = c1)
        cc1.place(x=210,y=0)
        c2 = ImageTk.PhotoImage(Image.open("images/triceps2.png"))
        cc2 = Label(topArms, image = c2)
        cc2.place(x=210,y=234)
        c3 = ImageTk.PhotoImage(Image.open("images/triceps3.png"))
        cc3 = Label(topArms, image = c3)
        cc3.place(x=210,y=468)
        cc.config( height = 250, width = 700, bd = 0)
    def dilbiai():
        c1 = ImageTk.PhotoImage(Image.open("images/dilbis1.png"))
        cc1 = Label(topArms, image = c1)
        cc1.place(x=210,y=0)
        c2 = ImageTk.PhotoImage(Image.open("images/dilbis2.png"))
        cc2 = Label(topArms, image = c2)
        cc2.place(x=210,y=234)
        c3 = ImageTk.PhotoImage(Image.open("images/dilbis3.png"))
        cc3 = Label(topArms, image = c3)
        cc3.place(x=210,y=468)
        cc.config( height = 250, width = 700, bd = 0)
        
    cbutton1 = Button(topArms, text = "Bicepso pratimai", command = bicepsai)
    cbutton1.place(x=30,y=50)
    cbutton1.config( height = 5, width = 20, bd = 2)
    cbutton2 = Button(topArms, text = "Tricepso pratimai")
    cbutton2.place(x=30,y=150)
    cbutton2.config( height = 5, width = 20, bd = 2, command = tricepsai)
    cbutton3 = Button(topArms, text = "Dilbio pratimai")
    cbutton3.place(x=30,y=250)
    cbutton3.config( height = 5, width = 20, bd = 2, command = dilbiai)
    first_textbox.grid(column=1, row=1)  
    third_textbox.grid(column=2, row=1, rowspan=2)
    topArms.mainloop()

root = Tk()

root.geometry("800x600")
root.title('Sporto pratimai')
root.resizable(width=False, height=False)

menubar = Menu(root)
formules = Menu(menubar, tearoff = 0) 
menubar.add_cascade(label ='Meniu', menu = formules) 
formules.add_command(label ='BMI skaičiuoklė', command = BMI) 
formules.add_command(label ='Dietos skaičiuoklė', command = dieta) 
formules.add_command(label ='Sporto pratimai', command = pratimai)
formules.add_command(label="Išeiti", command=root.quit)

apie = Menu(menubar, tearoff = 0) 
menubar.add_cascade(label ='Apie', menu = apie) 
apie.add_command(label ='Apie', command = message) 

root.config(menu = menubar)

label2 = Label(root, text="Įveskite ūgį (cm)")
label2.place(x=160, y=430)

background_image=tk.PhotoImage(file='images/fullbody.png')
background_label = tk.Label(root, image=background_image)
background_label.place(x=0, y=0, relwidth=1, relheight=1)

chest = PhotoImage(file = "images/chest.png")
btnChest = tk.Button(root, text="", command = openChest)
btnChest.place(x=140,y=101)
btnChest.config( height = 60, width = 126, bd = 0, image = chest)

back = PhotoImage(file = "images/back.png")
btnBack = tk.Button(root, text="", command = openBack)
btnBack.place(x=500,y=105)
btnBack.config( height = 135, width = 131, bd = 0, image = back)

aabs = PhotoImage(file = "images/abs.png")
btnAbs = tk.Button(root, text="", command = openAbs)
btnAbs.place(x=151,y=175)
btnAbs.config( height = 80, width = 101, bd = 0, image = aabs)

arms1 = PhotoImage(file = "images/leftarm.png")
btnAbs = tk.Button(root, text="", command = openArms)
btnAbs.place(x=86,y=135)
btnAbs.config( height = 130, width = 49, bd = 0, image = arms1)

arms2 = PhotoImage(file = "images/rightarm.png")
btnAbs = tk.Button(root, text="", command = openArms)
btnAbs.place(x=278,y=130)
btnAbs.config( height = 137, width = 70, bd = 0, image = arms2)

arms3 = PhotoImage(file = "images/backleftarm.png")
btnAbs = tk.Button(root, text="", command = openArms)
btnAbs.place(x=440,y=132)
btnAbs.config( height = 125, width = 47, bd = 0, image = arms3)

arms4 = PhotoImage(file = "images/backrightarm.png")
btnAbs = tk.Button(root, text="", command = openArms)
btnAbs.place(x=641,y=133)
btnAbs.config( height = 130, width = 42, bd = 0, image = arms4)



root.mainloop()